### ISSUE TITLE
Getting Fatal error: cfg not defined 

### ISSUE THREAD

**Issue by jzizka91** [Sarjuuk/aowow#421]
**Describe the bug and how to reproduce it**
additionally, paste relevant lines from db table  `aowow_errors`
or your browsers console here.

**Screenshots**

**System:**
 - OS: Linux (Ubuntu 24.04)
 - PHP version: 8
 - revision used: - 
 - Browser (in case of JavaScript / display errors): Chrome
 - AzerothCore: no
 
Hi.

This is my first time trying to run AoWoW and WoW database in general. For some reason whatever I do, I'm not able to run it successfully due to constantly getting an error: `Fatal error: cfg not defined: debug in /var/www/aowow/includes/config.class.php on line 154` when accessing the site.

I already ran out of ideas what I'm doing wrong. Apart from the `cfg not defined` I'm not monitoring any errors.

I'm running AoWoW in dev environment using docker-compose:

```
services:
  nginx:
    image: nginx:latest
    container_name: aowow_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./aowow:/var/www/aowow
    ports:
      - "80:80"
    networks:
      - aowow-net
    depends_on:
      - php
      - mysql

  mysql:
    image: mysql:5.7
    container_name: aowow_mysql
    environment:
      MYSQL_DATABASE: aowow
      MYSQL_ROOT_PASSWORD: root-example
      MYSQL_USER: aowow_user
      MYSQL_PASSWORD: aowow_user-example
    volumes:
      - mysql_data:/var/lib/mysql
      - ./aowow:/var/www/aowow
    networks:
      - aowow-net

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aowow_php
    volumes:
      - ./aowow:/var/www/aowow
    networks:
      - aowow-net

networks:
  aowow-net:

volumes:
  mysql_data:
  
 ```
To connect with the database I'm using setup/config.php

```
<?php

if (!defined('AOWOW_REVISION'))
    die('illegal access');

$AoWoWconf = [
    'aowow' => [
        'host' => 'mysql',
        'user' => 'root',
        'pass' => 'root-example',
        'db'   => 'aowow'
    ]
];

?>
```

An important note. I didn't run the initial setup yet (`php aowow --setup`). It won't allow me to run it. The setup returns the same error.
